name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Triggers on changes in the frontend directory

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Koristi verziju Node.js koja je kompatibilna sa tvojim projektom

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules  # Keširaj npm zavisnosti
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}  # Ključ baziran na hash-u `package-lock.json`
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install
        working-directory: frontend  # Promeni radni direktorijum na `frontend`

      - name: Build frontend
        run: npm run build  # Buildanje aplikacije
        working-directory: frontend  # Promeni radni direktorijum na `frontend`

      - name: Deploy frontend (ako je potrebno)
        run: |
          echo "Deploying the frontend..."
