name: Build and Push Frontend Image

on:
  push:
    branches:
      - master
    paths:
      - 'IzvorniKod/jollybringer-frontend/**'  # Trigger only on changes u `IzvorniKod/jollybringer-frontend`
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Koristi verziju Node.js koja je kompatibilna sa tvojim projektom

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: IzvorniKod/jollybringer-frontend/node_modules  # Keširaj npm zavisnosti
          key: ${{ runner.os }}-npm-${{ hashFiles('IzvorniKod/jollybringer-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install
        working-directory: IzvorniKod/jollybringer-frontend  # Postavi radni direktorijum na `IzvorniKod/jollybringer-frontend`

      - name: Install Vite manually
        run: npm install vite --save-dev
        working-directory: IzvorniKod/jollybringer-frontend  # Postavi radni direktorijum na `IzvorniKod/jollybringer-frontend`

      - name: Install React plugin for Vite
        run: npm install @vitejs/plugin-react --save-dev
        working-directory: IzvorniKod/jollybringer-frontend  # Postavi radni direktorijum na `IzvorniKod/jollybringer-frontend`

      - name: Set executable permissions for Vite
        run: chmod +x node_modules/.bin/vite
        working-directory: IzvorniKod/jollybringer-frontend

      - name: Build frontend
        run: npm run build
        working-directory: IzvorniKod/jollybringer-frontend  # Postavi radni direktorijum na `IzvorniKod/jollybringer-frontend`

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./IzvorniKod/jollybringer-frontend
          file: ./IzvorniKod/jollybringer-frontend/Dockerfile
          push: true
          tags: ghcr.io/petarkapec/jollybringer-frontend:latest  # Koristi samo mala slova


      - name: Trigger release
        if: ${{ env.FRONTEND_DEPLOY_HOOK }}
        run: curl ${{ env.FRONTEND_DEPLOY_HOOK }}
